"""
Export the complete local MySQL `crimevision_db` schema to schema.sql.

Why this exists:
    `initialize_schema()` in app/core/database.py only creates the tables it
    explicitly defines (~12). Your local DB has more (e.g. `crimes`) plus
    extra columns added manually over time. This script dumps everything
    so you can recreate the same schema on TiDB Cloud (or any other host).

Usage:
    cd CrimeVision/backend
    python export_local_schema.py

    Prompts for your local MySQL password (no hardcoded secrets, no PATH
    setup, no mysqldump needed). Writes schema.sql in the current folder.

Then in TiDB SQL Editor:
    USE crimevision_db;
    -- paste the entire contents of schema.sql, then run.
"""
from __future__ import annotations

import getpass
import sys

import mysql.connector
from mysql.connector import Error


LOCAL_HOST = "localhost"
LOCAL_PORT = 3306
LOCAL_USER = "root"
LOCAL_DATABASE = "crimevision_db"

OUTPUT_FILE = "schema.sql"


def export_schema() -> None:
    print(f"Connecting to local MySQL at {LOCAL_HOST}:{LOCAL_PORT} as {LOCAL_USER}...")
    password = getpass.getpass("Local MySQL password: ")

    try:
        conn = mysql.connector.connect(
            host=LOCAL_HOST,
            port=LOCAL_PORT,
            user=LOCAL_USER,
            password=password,
            database=LOCAL_DATABASE,
        )
    except Error as exc:
        print(f"ERROR: could not connect to local MySQL: {exc}")
        sys.exit(1)

    cursor = conn.cursor()

    cursor.execute("SHOW TABLES")
    tables = [row[0] for row in cursor.fetchall()]
    print(f"Found {len(tables)} tables: {', '.join(tables)}")

    lines: list[str] = [
        "-- =====================================================================",
        f"-- CrimeVision schema dump — {len(tables)} tables",
        "-- Generated by export_local_schema.py",
        "-- =====================================================================",
        "",
        "-- Disable foreign key checks during import so table order doesn't matter.",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "",
    ]

    for table in tables:
        cursor.execute(f"SHOW CREATE TABLE `{table}`")
        row = cursor.fetchone()
        if not row:
            continue
        ddl = row[1]
        lines.append(f"-- ----------------------------------------")
        lines.append(f"-- Table: {table}")
        lines.append(f"-- ----------------------------------------")
        lines.append(f"DROP TABLE IF EXISTS `{table}`;")
        lines.append(f"{ddl};")
        lines.append("")

    cursor.execute("SHOW TRIGGERS")
    triggers = cursor.fetchall()
    if triggers:
        lines.append("-- ----------------------------------------")
        lines.append("-- Triggers")
        lines.append("-- ----------------------------------------")
        for trigger in triggers:
            trigger_name = trigger[0]
            cursor.execute(f"SHOW CREATE TRIGGER `{trigger_name}`")
            trow = cursor.fetchone()
            if trow:
                lines.append(f"DROP TRIGGER IF EXISTS `{trigger_name}`;")
                lines.append(f"DELIMITER //")
                lines.append(f"{trow[2]}//")
                lines.append(f"DELIMITER ;")
                lines.append("")

    lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    lines.append("")

    cursor.close()
    conn.close()

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\nWrote {OUTPUT_FILE} ({len(tables)} tables, {len(triggers)} triggers).")
    print("\nNext steps:")
    print(f"  1. Open {OUTPUT_FILE} and review it.")
    print("  2. Open TiDB Cloud → SQL Editor.")
    print("  3. Run:  USE crimevision_db;")
    print(f"  4. Paste the contents of {OUTPUT_FILE} and click Run.")


if __name__ == "__main__":
    export_schema()
